### PR TITLE
Bumped vagrant version. Removed extra lines in Makefile

### LINKED ISSUE #50: Bump vagrant-hashistack version 0.4.3 -> 0.5.0
https://github.com/fredrikhgrelland/vagrant-hashistack-template/blob/master/Vagrantfile.default#L3

### PR DESCRIPTION
**Pull request by claesgill**
Closes #50 

- Bumped vagrant version
- Removed duplicated lines in Makefile

### CODE REVIEW

**Review by pdmthorsrud — APPROVED** [review]

**Comment by claesgill** [comment]
@zhenik @pdmthorsrud @dangernil 
I see that we get a error regarding booting.
Error:
```sh
If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
make: *** [template_example] Error 1
Error: Process completed with exit code 2.
```

My question is, should I set the `config.vm.boot_timeout` to some value that we can consider default? Maybe `300`?

**Comment by zhenik** [comment]
Presto module has 600
https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/Vagrantfile.default#L4

**Comment by claesgill** [comment]
> Presto module has 600
> https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/Vagrantfile.default#L4

Should we use a default of `600` then?

**Comment by zhenik** [comment]
> > Presto module has 600
> > https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/Vagrantfile.default#L4
> 
> Should we use a default of `600` then?

Lets try 600.

**Review by zhenik — APPROVED** [review]

**Pull request merged**
