### PR TITLE
Fixed box ansible args

### LINKED ISSUE #57: Make dev running all ansible tests
Issue with `make dev` that runs all ansible-playbooks with `tag=test` although `ANSIBLE_ARGS='--skip-tags "test"` is set.

### PR DESCRIPTION
**Pull request by claesgill**
## Closes/fixes/resolves issue(s)?
Closes #57 

## What was added/changed/fixed?
- Fixed that box can receive Ansible arguments

## Checklist (after created PR)
- [x] Added reviewers
- [x] Added assignee(s)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

### CODE REVIEW

**Comment by zhenik** [comment]
@claesgill I think the box has support it already https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/packer/Vagrantfile#L20

**Review by dangernil — APPROVED** [review]

**Comment by claesgill** [comment]
> @claesgill I think the box has support it already https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/packer/Vagrantfile#L20

Box is supported, but missing in this repos Vagrant.default file. Doesn't work without it

**Comment by zhenik** [comment]
> > @claesgill I think the box has support it already https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/packer/Vagrantfile#L20
> 
> Box is supported, but missing in this repos Vagrant.default file. Doesn't work without it

Does it mean, that cmd `make dev` actually never skips tasks with `tags: test` in all modules?

**Comment by claesgill** [comment]
> > > @claesgill I think the box has support it already https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/packer/Vagrantfile#L20
> > 
> > 
> > Box is supported, but missing in this repos Vagrant.default file. Doesn't work without it
> 
> Does it mean, that cmd `make dev` actually never skips tasks with `tags: test` in all modules?

Jupp

**Review by zhenik — APPROVED** [review]

**Comment by pdmthorsrud** [comment]
> > > > @claesgill I think the box has support it already https://github.com/fredrikhgrelland/vagrant-hashistack/blob/master/packer/Vagrantfile#L20
> > > 
> > > 
> > > Box is supported, but missing in this repos Vagrant.default file. Doesn't work without it
> > 
> > 
> > Does it mean, that cmd `make dev` actually never skips tasks with `tags: test` in all modules?
> 
> Jupp

This is also something I had to fix in https://github.com/fredrikhgrelland/terraform-nomad-presto/pull/74 as well!

**Review by pdmthorsrud — APPROVED** [review]

**Pull request merged**
