### PR TITLE
Added getting started section

### PR DESCRIPTION
**Pull request by pdmthorsrud**
Creating new PR because the other one got absolutely botched by something I've done wrong somewhere in the git history.

### CODE REVIEW

**Comment by pdmthorsrud** [comment]
This PR is not finished, but I realised I've done a lot without checking in with you guys. Do you feel like this is going in the right direction? 

You don't have to do spellchecking and syntax-checks atm, but more the overall structure and flow + if I'm missing some key sections

**Comment by zhenik** [comment]
> This PR is not finished, but I realised I've done a lot without checking in with you guys. Do you feel like this is going in the right direction?
> 
> You don't have to do spellchecking and syntax-checks atm, but more the overall structure and flow + if I'm missing some key sections

Before we had a discussion about to extract `Getting started` context in a separate doc file. WDYT about it?

**Comment by pdmthorsrud** [comment]
> > This PR is not finished, but I realised I've done a lot without checking in with you guys. Do you feel like this is going in the right direction?
> > You don't have to do spellchecking and syntax-checks atm, but more the overall structure and flow + if I'm missing some key sections
> 
> Before we had a discussion about to extract `Getting started` context in a separate doc file. WDYT about it?

Considering how large it is getting, I still think this is a good idea. I will do it

**Comment by pdmthorsrud** [comment]
FYI: This is supposed to be a detailed guide to learn and explain how, why and what. 

We should have a simple numbered list that lays out all the steps necessary to create a module somewhere else, that can be used as reference. This guide is not meant as a reference or an item you use to check "how did I push images to MinIO again?". That we already have

**Comment by pdmthorsrud** [comment]
This was deleted because the branch was deleted. Will be replaced by two separate PRs shortly

**Pull request closed without merging**
