### PR TITLE
Add terraform-provider-vault token

### LINKED ISSUE #35: Missing token for terraform-provider-vault
## Description
**Blocker for [#368](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/368)**

Once [default tokens will be removed](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/368) all terraform communications with hashistack cluster will be via [providers](https://www.terraform.io/docs/providers/index.html):

- [terraform-provider-nomad](https://registry.terraform.io/providers/hashicorp/nomad/latest/docs)
- [terraform-provider-vault](https://registry.terraform.io/providers/hashicorp/vault/latest/docs)
- [terraform-provider-consul](https://registry.terraform.io/providers/hashicorp/consul/latest/docs)

## Problem
When default tokens remove, we need to provide credentials for [terraform-provider-vault](https://registry.terraform.io/providers/hashicorp/vault/latest/docs)

## Logs
```
TASK [Terraform] ***************************************************************
fatal: [default]: FAILED! => {
    "changed": false
}

MSG:

Terraform plan could not be created
STDOUT: Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vault_generic_secret.nomad_secret_id[0]: Refreshing state...


STDERR: 
Error: no secret found at "nomad/creds/write"

  on nomad_acl.tf line 1, in data "vault_generic_secret" "nomad_secret_id":
   1: data "vault_generic_secret" "nomad_secret_id" {




PLAY RECAP *********************************************************************
default                    : ok=7    changed=3    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
make[2]: *** [template_example] Error 1
make[1]: *** [up] Error 2
make: *** [test] Error 2
Error: Process completed with exit code 2.
2s
```

Ref: [Logs with problems](https://github.com/fredrikhgrelland/vagrant-hashistack/pull/373/checks?check_run_id=1213946936#step:9:500)

### PR DESCRIPTION
**Pull request by zhenik**

### CODE REVIEW

**Comment by pdmthorsrud** [comment]
~~Looks good, but isn't this already set as `VAULT_TOKEN` in the box, which the provider would automatically use?~~
Edit: Oh, this is relation to #35, and the fact that you're removing default. Sorry, didn't realise

**Review by pdmthorsrud — APPROVED** [review]

**Comment by zhenik** [comment]
> Looks good, but isn't this already set as `VAULT_TOKEN` in the box, which the provider would automatically use?

:) That is correct and soon it will be removed [#368](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/368).
The box should simulate real prod env like there are no env variables for tokens available by default.

**Comment by Neha-Sinha2305** [comment]
@zhenik : Looks good, however, one question that i have is how do we know that this solution works?
As in the tests are green but i also see that the env variables exists as well:
```
        "VAULT_ADDR": "http://127.0.0.1:8200",
        "VAULT_TOKEN": "master",
```
I guess you would have tested it locally by removing these env variables, if thta's the case then it's good to merge this fix.

**Comment by zhenik** [comment]
> @zhenik : Looks good, however, one question that i have is how do we know that this solution works?
> As in the tests are green but i also see that the env variables exists as well:
> 
> ```
>         "VAULT_ADDR": "http://127.0.0.1:8200",
>         "VAULT_TOKEN": "master",
> ```
> 
> I guess you would have tested it locally by removing these env variables, if thta's the case then it's good to merge this fix.

Yes, I tested it locally, due that box and template decoupled. Current PR is a blocker for https://github.com/fredrikhgrelland/vagrant-hashistack/pull/373#issuecomment-704156202 

After this PR will be merged, I will update the commit pointer in the box PR #373 and continue development. Current changes will be tested in the box PR #373 CD/CI

**Review by Neha-Sinha2305 — APPROVED** [review]
LGTM

**Pull request merged**
